[package]
name = "rust_kvm_experiment"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = { version = "0.5.3", features = ["serialize", "unstable_grab"] }
eframe = "0.27.2"
serde = { version = "1.0", features = ["derive"] }
local-ip-address = "0.6.1"
